import house from "@/public/propertyhouse.svg";
import house2 from "@/public/house2.svg";
import house3 from "@/public/house3.svg";
import house4 from "@/public/house4.svg";
import luxury from "@/public/Luxury Modern Villa.jpg";
import modern from "@/public/Luxury Modern Villa1.jpg";
import villa from "@/public/Luxury Modern Villa2.jpg";
import elder from "@/public/elderrealestate.svg";
import ana from "@/public/anajonesagent.svg";
import type { ListingProperty } from "@/lib/properties/types";
import {
  luxuryClockIcon,
  luxurySqftIcon,
  luxuryLocationIcon,
  luxurylikedicon,
  luxurylikeicon,
  luxuryPropertyFeatureIcons,
  rentPropertyFeatureIcons,
} from "@/lib/properties/property-card-icons";

const LUXURY_HOVER_BORDER_GRADIENT =
  "linear-gradient(90deg, #CB9E33, #EDD06A, #FCEA94, #FADE7B, #FDEE9D, #C29225)";

const createRentSectionCard = (
  property: Omit<ListingProperty, "thumbnail" | "socials" | "flags">,
): ListingProperty => ({
  ...property,
  thumbnail: property.images,
  socials: [],
  flags: [],
});

export const newlyListedRentProperties: ListingProperty[] = [
  createRentSectionCard({
    id: "101",
    images: [house, house2],
    location: "Richmond, VIC 3121",
    size: "1,050",
    date: "18-02-2026",
    time: "09:30",
    priceRange: "$700/week",
    propertyType: "Apartment",
    agentName: "Anna Johns",
    agentCompany: elder,
    agentCompanyName: "Parker Realestate",
    agentLocation: "Melbourne, Australia",
    agentPhone: "+9999999999",
    agentEmail: "xyz@email.com",
    agentImage: ana,
    agentImageCard: ana,
    renticonImages: rentPropertyFeatureIcons,
    iconLabels: ["1", "1", "1"],
    detailHref: "/property/101?listingVariant=rent",
  }),
  createRentSectionCard({
    id: "102",
    images: [house4, house3],
    location: "Parramatta, NSW 2150",
    size: "1,240",
    date: "20-02-2026",
    time: "11:00",
    priceRange: "$820/week",
    propertyType: "Townhouse",
    agentName: "Anna Johns",
    agentCompany: elder,
    agentCompanyName: "Parker Realestate",
    agentLocation: "Sydney, Australia",
    agentPhone: "+9999999999",
    agentEmail: "xyz@email.com",
    agentImage: ana,
    agentImageCard: ana,
    renticonImages: rentPropertyFeatureIcons,
    iconLabels: ["1", "1", "1"],
    detailHref: "/property/102?listingVariant=rent",
  }),
  createRentSectionCard({
    id: "103",
    images: [house2, house4],
    location: "Newstead, QLD 4006",
    size: "980",
    date: "22-02-2026",
    time: "14:00",
    priceRange: "$640/week",
    propertyType: "Apartment",
    agentName: "Anna Johns",
    agentCompany: elder,
    agentCompanyName: "Parker Realestate",
    agentLocation: "Brisbane, Australia",
    agentPhone: "+9999999999",
    agentEmail: "xyz@email.com",
    agentImage: ana,
    agentImageCard: ana,
    renticonImages: rentPropertyFeatureIcons,
    iconLabels: ["1", "1", "1"],
    detailHref: "/property/103?listingVariant=rent",
  }),
  createRentSectionCard({
    id: "104",
    images: [house3, house],
    location: "Glenelg, SA 5045",
    size: "1,180",
    date: "24-02-2026",
    time: "15:30",
    priceRange: "$590/week",
    propertyType: "House",
    agentName: "Anna Johns",
    agentCompany: elder,
    agentCompanyName: "Parker Realestate",
    agentLocation: "Adelaide, Australia",
    agentPhone: "+9999999999",
    agentEmail: "xyz@email.com",
    agentImage: ana,
    agentImageCard: ana,
    renticonImages: rentPropertyFeatureIcons,
    iconLabels: ["1", "1", "1"],
    detailHref: "/property/104?listingVariant=rent",
  }),
];

export const trendingRentProperties: ListingProperty[] = [
  createRentSectionCard({
    id: "111",
    images: [house4, house],
    location: "Bondi Beach, NSW 2026",
    size: "1,320",
    date: "26-02-2026",
    time: "10:15",
    priceRange: "$950/week",
    propertyType: "Apartment",
    agentName: "Anna Johns",
    agentCompany: elder,
    agentCompanyName: "Parker Realestate",
    agentLocation: "Sydney, Australia",
    agentPhone: "+9999999999",
    agentEmail: "xyz@email.com",
    agentImage: ana,
    agentImageCard: ana,
    renticonImages: rentPropertyFeatureIcons,
    iconLabels: ["1", "1", "1"],
    detailHref: "/property/111?listingVariant=rent",
  }),
  createRentSectionCard({
    id: "112",
    images: [house, house3],
    location: "Southbank, VIC 3006",
    size: "1,410",
    date: "27-02-2026",
    time: "12:00",
    priceRange: "$880/week",
    propertyType: "Apartment",
    agentName: "Anna Johns",
    agentCompany: elder,
    agentCompanyName: "Parker Realestate",
    agentLocation: "Melbourne, Australia",
    agentPhone: "+9999999999",
    agentEmail: "xyz@email.com",
    agentImage: ana,
    agentImageCard: ana,
    renticonImages: rentPropertyFeatureIcons,
    iconLabels: ["1", "1", "1"],
    detailHref: "/property/112?listingVariant=rent",
  }),
  createRentSectionCard({
    id: "113",
    images: [house3, house2],
    location: "Subiaco, WA 6008",
    size: "1,560",
    date: "28-02-2026",
    time: "13:45",
    priceRange: "$760/week",
    propertyType: "Townhouse",
    agentName: "Anna Johns",
    agentCompany: elder,
    agentCompanyName: "Parker Realestate",
    agentLocation: "Perth, Australia",
    agentPhone: "+9999999999",
    agentEmail: "xyz@email.com",
    agentImage: ana,
    agentImageCard: ana,
    renticonImages: rentPropertyFeatureIcons,
    iconLabels: ["1", "1", "1"],
    detailHref: "/property/113?listingVariant=rent",
  }),
  createRentSectionCard({
    id: "114",
    images: [house2, house4],
    location: "Battery Point, TAS 7004",
    size: "1,090",
    date: "01-03-2026",
    time: "16:00",
    priceRange: "$620/week",
    propertyType: "House",
    agentName: "Anna Johns",
    agentCompany: elder,
    agentCompanyName: "Parker Realestate",
    agentLocation: "Hobart, Australia",
    agentPhone: "+9999999999",
    agentEmail: "xyz@email.com",
    agentImage: ana,
    agentImageCard: ana,
    renticonImages: rentPropertyFeatureIcons,
    iconLabels: ["1", "1", "1"],
    detailHref: "/property/114?listingVariant=rent",
  }),
];

export const luxuryRentProperties: ListingProperty[] = [
  createRentSectionCard({
    id: "121",
    images: [modern, luxury],
    location: "Toorak, VIC 3142",
    size: "3,850",
    date: "04-03-2026",
    time: "10:30",
    priceRange: "$2,400/week",
    propertyType: "Villa",
    agentName: "Anna Johns",
    agentCompany: elder,
    agentCompanyName: "Parker Realestate",
    agentLocation: "Melbourne, Australia",
    agentPhone: "+9999999999",
    agentEmail: "xyz@email.com",
    agentImage: ana,
    agentImageCard: ana,
    renticonImages: luxuryPropertyFeatureIcons,
    iconLabels: ["1", "1", "1"],
    locationIcon: luxuryLocationIcon,
    clockIcon: luxuryClockIcon,
    sizeIcon: luxurySqftIcon,
    likeIcon: luxurylikeicon,
    likedIcon: luxurylikedicon,
    hoverBorderGradient: LUXURY_HOVER_BORDER_GRADIENT,
    detailHref: "/property/121?listingVariant=rent",
  }),
  createRentSectionCard({
    id: "122",
    images: [villa, luxury],
    location: "Vaucluse, NSW 2030",
    size: "4,120",
    date: "05-03-2026",
    time: "12:30",
    priceRange: "$2,900/week",
    propertyType: "House",
    agentName: "Anna Johns",
    agentCompany: elder,
    agentCompanyName: "Parker Realestate",
    agentLocation: "Sydney, Australia",
    agentPhone: "+9999999999",
    agentEmail: "xyz@email.com",
    agentImage: ana,
    agentImageCard: ana,
    renticonImages: luxuryPropertyFeatureIcons,
    iconLabels: ["1", "1", "1"],
    locationIcon: luxuryLocationIcon,
    clockIcon: luxuryClockIcon,
    sizeIcon: luxurySqftIcon,
    likeIcon: luxurylikeicon,
    likedIcon: luxurylikedicon,
    hoverBorderGradient: LUXURY_HOVER_BORDER_GRADIENT,
    detailHref: "/property/122?listingVariant=rent",
  }),
  createRentSectionCard({
    id: "123",
    images: [modern, villa],
    location: "Noosa Heads, QLD 4567",
    size: "3,640",
    date: "06-03-2026",
    time: "14:30",
    priceRange: "$2,100/week",
    propertyType: "Villa",
    agentName: "Anna Johns",
    agentCompany: elder,
    agentCompanyName: "Parker Realestate",
    agentLocation: "Noosa, Australia",
    agentPhone: "+9999999999",
    agentEmail: "xyz@email.com",
    agentImage: ana,
    agentImageCard: ana,
    renticonImages: luxuryPropertyFeatureIcons,
    iconLabels: ["1", "1", "1"],
    locationIcon: luxuryLocationIcon,
    clockIcon: luxuryClockIcon,
    sizeIcon: luxurySqftIcon,
    likeIcon: luxurylikeicon,
    likedIcon: luxurylikedicon,
    hoverBorderGradient: LUXURY_HOVER_BORDER_GRADIENT,
    detailHref: "/property/123?listingVariant=rent",
  }),
  createRentSectionCard({
    id: "124",
    images: [luxury, modern],
    location: "Mosman Park, WA 6012",
    size: "3,980",
    date: "07-03-2026",
    time: "15:30",
    priceRange: "$2,250/week",
    propertyType: "House",
    agentName: "Anna Johns",
    agentCompany: elder,
    agentCompanyName: "Parker Realestate",
    agentLocation: "Perth, Australia",
    agentPhone: "+9999999999",
    agentEmail: "xyz@email.com",
    agentImage: ana,
    agentImageCard: ana,
    renticonImages: luxuryPropertyFeatureIcons,
    iconLabels: ["1", "1", "1"],
    locationIcon: luxuryLocationIcon,
    clockIcon: luxuryClockIcon,
    sizeIcon: luxurySqftIcon,
    likeIcon: luxurylikeicon,
    likedIcon: luxurylikedicon,
    hoverBorderGradient: LUXURY_HOVER_BORDER_GRADIENT,
    detailHref: "/property/124?listingVariant=rent",
  }),
];
