import type { CommercialListing } from "./types";

import internationaltower from "@/public/international tower.jpg";
import port from "@/public/port melbourn.jpg";
import collins from "@/public/collins Street.jpg";
import commercialimg1 from "@/public/commercialimg1.jpg";
import new1 from "@/public/new1.svg";
import new2 from "@/public/new2.svg";
import new3 from "@/public/new3.svg";
import agent1 from "@/public/agentimg1.jpg";
import agent2 from "@/public/agentimg2.jpg";
import agent3 from "@/public/agentimg3.jpg";
import workspace from "@/public/workspace.jpg";
import store from "@/public/store.jpg";
import storage from "@/public/storage.jpg";
import davidThompson from "@/public/davidthompson.jpg";
import lisaAnderson from "@/public/lisaAnderson.jpg";
import jenniferMartinez from "@/public/jennifermartinez.jpg";
import michaelChen from "@/public/michaelchen.jpg";
import saraJohnson from "@/public/sarajohnson.jpg";
import officesPhoto from "@/public/offices.jpg";
import warehousePhoto from "@/public/warehouse.jpg";
import shopsPhoto from "@/public/shops.jpg";

const description =
  "A premium commercial opportunity offering flexible floor plates, excellent natural light, and easy access to public transport and major arterial roads. Ideal for businesses seeking a high-profile address with strong exposure and on-site parking.";

export const commercialListings: CommercialListing[] = [
  {
    id: "1",
    title: "International Towers, Sydney",
    propertyType: "Office",
    listingType: "Lease",
    address: "Barangaroo, NSW 2000",
    location: "Barangaroo, NSW 2000",
    price: "Contact for pricing",
    size: "1,200",
    carSpaces: "45",
    day: "Monday",
    date: "08.06.2026",
    time: "10:30",
    thumbnail: internationaltower,
    gallery: [internationaltower, commercialimg1, new1],
    description,
    agent: {
      name: "John Citizen",
      phone: "0400 123 456",
      email: "John.Citizen@niemeyer.com.au",
      image: agent1,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "2",
    title: "Port Melbourne Logistics Hub",
    propertyType: "Warehouse",
    listingType: "Buy",
    address: "Port Melbourne, VIC 3207",
    location: "Port Melbourne, VIC 3207",
    price: "Contact for pricing",
    size: "1,200",
    carSpaces: "45",
    day: "Tuesday",
    date: "09.06.2026",
    time: "02:00",
    thumbnail: port,
    gallery: [port, commercialimg1, new2],
    description,
    agent: {
      name: "Sarah Connor",
      phone: "0422 987 654",
      email: "Sarah.Connor@niemeyer.com.au",
      image: agent2,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "3",
    title: "Collins Street Luxury Retail",
    propertyType: "Retail",
    listingType: "Buy",
    address: "Collins Street, Melbourne VIC 3000",
    location: "Collins Street, Melbourne VIC 3000",
    price: "Contact for pricing",
    size: "1,200",
    carSpaces: "45",
    day: "Wednesday",
    date: "10.06.2026",
    time: "11:00",
    thumbnail: collins,
    gallery: [collins, commercialimg1, new3],
    description,
    agent: {
      name: "Michael Chang",
      phone: "0433 555 777",
      email: "Michael.Chang@niemeyer.com.au",
      image: agent3,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-1",
    title: "King George Street Warehouse",
    propertyType: "Warehouse",
    listingType: "Lease",
    address: "500 King George Street, Sydney NSW 2000",
    location: "Sydney NSW 2000",
    price: "$100,000",
    size: "850",
    carSpaces: "2",
    day: "Monday",
    date: "08.06.2026",
    time: "10:30",
    thumbnail: new1,
    gallery: [new1, new2, new3],
    description,
    agent: {
      name: "John Citizen",
      phone: "0400 123 456",
      email: "John.Citizen@niemeyer.com.au",
      image: agent1,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-2",
    title: "Collins Street Retail Suite",
    propertyType: "Retail",
    listingType: "Buy",
    address: "12 Collins Street, Melbourne VIC 3000",
    location: "Melbourne VIC 3000",
    price: "$250,000",
    size: "1,200",
    carSpaces: "4",
    day: "Tuesday",
    date: "09.06.2026",
    time: "02:00",
    thumbnail: new2,
    gallery: [new2, new3, new1],
    description,
    agent: {
      name: "Sarah Connor",
      phone: "0422 987 654",
      email: "Sarah.Connor@niemeyer.com.au",
      image: agent2,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-3",
    title: "Barangaroo Avenue Office",
    propertyType: "Office",
    listingType: "Buy",
    address: "88 Barangaroo Avenue, Sydney NSW 2000",
    location: "Sydney NSW 2000",
    price: "$1,800,000",
    size: "2,500",
    carSpaces: "8",
    day: "Wednesday",
    date: "10.06.2026",
    time: "11:00",
    thumbnail: new3,
    gallery: [new3, new1, new2],
    description,
    agent: {
      name: "Michael Chang",
      phone: "0433 555 777",
      email: "Michael.Chang@niemeyer.com.au",
      image: agent3,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-4",
    title: "Main North Road Showroom",
    propertyType: "Showroom",
    listingType: "Lease",
    address: "104 Main North Road, Medindie SA 5081",
    location: "Medindie SA 5081",
    price: "$85,000",
    size: "450",
    carSpaces: "1",
    day: "Thursday",
    date: "11.06.2026",
    time: "09:30",
    thumbnail: new1,
    gallery: [new1, new3, new2],
    description,
    agent: {
      name: "Emily Rodriguez",
      phone: "0455 111 222",
      email: "Emily.Rodriguez@niemeyer.com.au",
      image: agent1,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-5",
    title: "Chapel Street Retail Space",
    propertyType: "Retail",
    listingType: "Lease",
    address: "220 Chapel Street, Prahran VIC 3181",
    location: "Prahran VIC 3181",
    price: "$65,000",
    size: "680",
    carSpaces: "2",
    day: "Friday",
    date: "12.06.2026",
    time: "01:00",
    thumbnail: store,
    gallery: [store, commercialimg1, new2],
    description,
    agent: {
      name: "David Thompson",
      phone: "0466 222 333",
      email: "David.Thompson@niemeyer.com.au",
      image: davidThompson,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-6",
    title: "Bondi Junction Showroom",
    propertyType: "Showroom",
    listingType: "Buy",
    address: "45 Oxford Street, Bondi Junction NSW 2022",
    location: "Bondi Junction NSW 2022",
    price: "$1,150,000",
    size: "900",
    carSpaces: "3",
    day: "Saturday",
    date: "13.06.2026",
    time: "10:00",
    thumbnail: store,
    gallery: [store, new1, commercialimg1],
    description,
    agent: {
      name: "Lisa Anderson",
      phone: "0477 333 444",
      email: "Lisa.Anderson@niemeyer.com.au",
      image: lisaAnderson,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-7",
    title: "Southbank Coworking Suite",
    propertyType: "Workspace",
    listingType: "Buy",
    address: "1 Southbank Boulevard, Southbank VIC 3006",
    location: "Southbank VIC 3006",
    price: "$980,000",
    size: "1,050",
    carSpaces: "5",
    day: "Sunday",
    date: "14.06.2026",
    time: "12:30",
    thumbnail: workspace,
    gallery: [workspace, commercialimg1, new3],
    description,
    agent: {
      name: "Jennifer Martinez",
      phone: "0488 444 555",
      email: "Jennifer.Martinez@niemeyer.com.au",
      image: jenniferMartinez,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-8",
    title: "Docklands Flexi Workspace",
    propertyType: "Workspace",
    listingType: "Lease",
    address: "800 Bourke Street, Docklands VIC 3008",
    location: "Docklands VIC 3008",
    price: "$72,000",
    size: "620",
    carSpaces: "2",
    day: "Monday",
    date: "15.06.2026",
    time: "09:00",
    thumbnail: workspace,
    gallery: [workspace, new1, new2],
    description,
    agent: {
      name: "David Thompson",
      phone: "0466 222 333",
      email: "David.Thompson@niemeyer.com.au",
      image: davidThompson,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-9",
    title: "Eastern Creek Storage Facility",
    propertyType: "Storage",
    listingType: "Buy",
    address: "18 Distribution Drive, Eastern Creek NSW 2766",
    location: "Eastern Creek NSW 2766",
    price: "$2,300,000",
    size: "4,500",
    carSpaces: "12",
    day: "Tuesday",
    date: "16.06.2026",
    time: "08:30",
    thumbnail: storage,
    gallery: [storage, commercialimg1, new1],
    description,
    agent: {
      name: "Lisa Anderson",
      phone: "0477 333 444",
      email: "Lisa.Anderson@niemeyer.com.au",
      image: lisaAnderson,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-10",
    title: "Altona Self-Storage Units",
    propertyType: "Storage",
    listingType: "Lease",
    address: "5 Cargo Road, Altona VIC 3018",
    location: "Altona VIC 3018",
    price: "$40,000",
    size: "1,800",
    carSpaces: "6",
    day: "Wednesday",
    date: "17.06.2026",
    time: "03:00",
    thumbnail: storage,
    gallery: [storage, new2, new3],
    description,
    agent: {
      name: "Jennifer Martinez",
      phone: "0488 444 555",
      email: "Jennifer.Martinez@niemeyer.com.au",
      image: jenniferMartinez,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-11",
    title: "Southbank Executive Offices",
    propertyType: "Office",
    listingType: "Lease",
    address: "30 City Road, Southbank VIC 3006",
    location: "Southbank VIC 3006",
    price: "$95,000",
    size: "1,600",
    carSpaces: "10",
    day: "Thursday",
    date: "18.06.2026",
    time: "09:00",
    thumbnail: officesPhoto,
    gallery: [officesPhoto, commercialimg1, new2],
    description,
    agent: {
      name: "Michael Chen",
      phone: "0499 555 666",
      email: "Michael.Chen@niemeyer.com.au",
      image: michaelChen,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-12",
    title: "Elizabeth Quay Office Tower",
    propertyType: "Office",
    listingType: "Buy",
    address: "150 St Georges Terrace, Perth WA 6000",
    location: "Perth WA 6000",
    price: "$3,200,000",
    size: "3,100",
    carSpaces: "15",
    day: "Friday",
    date: "19.06.2026",
    time: "01:30",
    thumbnail: officesPhoto,
    gallery: [officesPhoto, new1, commercialimg1],
    description,
    agent: {
      name: "Sara Johnson",
      phone: "0411 666 777",
      email: "Sara.Johnson@niemeyer.com.au",
      image: saraJohnson,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-13",
    title: "Yatala Distribution Centre",
    propertyType: "Warehouse",
    listingType: "Buy",
    address: "22 Enterprise Drive, Yatala QLD 4207",
    location: "Yatala QLD 4207",
    price: "$4,100,000",
    size: "6,200",
    carSpaces: "20",
    day: "Saturday",
    date: "20.06.2026",
    time: "07:30",
    thumbnail: warehousePhoto,
    gallery: [warehousePhoto, commercialimg1, new3],
    description,
    agent: {
      name: "Michael Chen",
      phone: "0499 555 666",
      email: "Michael.Chen@niemeyer.com.au",
      image: michaelChen,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-14",
    title: "Wingfield Industrial Park",
    propertyType: "Warehouse",
    listingType: "Lease",
    address: "8 Grand Junction Road, Wingfield SA 5013",
    location: "Wingfield SA 5013",
    price: "$58,000",
    size: "2,900",
    carSpaces: "9",
    day: "Sunday",
    date: "21.06.2026",
    time: "10:15",
    thumbnail: warehousePhoto,
    gallery: [warehousePhoto, new2, new1],
    description,
    agent: {
      name: "Sara Johnson",
      phone: "0411 666 777",
      email: "Sara.Johnson@niemeyer.com.au",
      image: saraJohnson,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-15",
    title: "Surfers Paradise Retail Strip",
    propertyType: "Retail",
    listingType: "Lease",
    address: "3125 Surfers Paradise Boulevard, Surfers Paradise QLD 4217",
    location: "Surfers Paradise QLD 4217",
    price: "$78,000",
    size: "760",
    carSpaces: "3",
    day: "Monday",
    date: "22.06.2026",
    time: "11:45",
    thumbnail: shopsPhoto,
    gallery: [shopsPhoto, commercialimg1, new1],
    description,
    agent: {
      name: "David Thompson",
      phone: "0466 222 333",
      email: "David.Thompson@niemeyer.com.au",
      image: davidThompson,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-16",
    title: "Fremantle Boutique Showroom",
    propertyType: "Showroom",
    listingType: "Buy",
    address: "12 High Street, Fremantle WA 6160",
    location: "Fremantle WA 6160",
    price: "$920,000",
    size: "540",
    carSpaces: "2",
    day: "Tuesday",
    date: "23.06.2026",
    time: "02:00",
    thumbnail: store,
    gallery: [store, new3, commercialimg1],
    description,
    agent: {
      name: "Emily Rodriguez",
      phone: "0455 111 222",
      email: "Emily.Rodriguez@niemeyer.com.au",
      image: agent1,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-17",
    title: "Pyrmont Serviced Workspace",
    propertyType: "Workspace",
    listingType: "Lease",
    address: "50 Murray Street, Pyrmont NSW 2009",
    location: "Pyrmont NSW 2009",
    price: "$68,000",
    size: "580",
    carSpaces: "2",
    day: "Wednesday",
    date: "24.06.2026",
    time: "08:00",
    thumbnail: workspace,
    gallery: [workspace, commercialimg1, new2],
    description,
    agent: {
      name: "John Citizen",
      phone: "0400 123 456",
      email: "John.Citizen@niemeyer.com.au",
      image: agent1,
      agencyLogoText: "Niemeyer",
    },
  },
  {
    id: "commercial-18",
    title: "Salisbury Bulk Storage",
    propertyType: "Storage",
    listingType: "Buy",
    address: "6 Freight Street, Salisbury QLD 4107",
    location: "Salisbury QLD 4107",
    price: "$1,650,000",
    size: "3,300",
    carSpaces: "8",
    day: "Thursday",
    date: "25.06.2026",
    time: "09:45",
    thumbnail: storage,
    gallery: [storage, new1, new3],
    description,
    agent: {
      name: "Michael Chang",
      phone: "0433 555 777",
      email: "Michael.Chang@niemeyer.com.au",
      image: agent3,
      agencyLogoText: "Niemeyer",
    },
  },
];

export function getCommercialListingById(id: string) {
  return commercialListings.find((listing) => listing.id === id);
}

export function getRelatedCommercialListings(excludeId: string, limit = 5) {
  return commercialListings
    .filter((listing) => listing.id !== excludeId)
    .slice(0, limit);
}
