import type { AgentDetail } from "@/lib/agents/types";
import agencyLogo from "@/public/elderrealestate.svg";
import recommendAgent1 from "@/public/recommendagent1.jpg";
import recommendAgent2 from "@/public/recommendagent2.png";
import roomBg from "@/public/roombgimg.svg";
import breifcase from "@/public/breifcase.svg";
import building from "@/public/building.svg";

const baseBio =
  "Lorem ipsum dolor sit amet consectetur. Enim dolor est adipiscing consequat. Diam id auctor nunc sed id. Consectetur id risus tellus sed sed mi. Risus pretium proin nibh condimentum dui non. Lorem ipsum dolor sit amet consectetur. Elit adipiscing consequat. Diam id auctor nunc sed id. Consectetur id risus tellus est sed mi. Risus pretium proin nibh condimentum dui non.";

export const agentsCatalog: AgentDetail[] = [
  {
    id: "agent-1",
    slug: "katherine-fernandes",
    name: "Katherine Fernandes",
    title: "Senior Real Estate Agent",
    agencyName: "Elders Real Estate",
    agencyLogo,
    phone: "+9999999999",
    email: "exampleemail.com",
    location: "Austin, Australia",
    licenseNumber: "12345678",
    rating: 4.5,
    reviewCount: 38,
    avatar: recommendAgent1,
    backgroundImage: roomBg,
    cardVariant: "angled",
    accent: "red",
    yearsExperience: 9,
    propertiesSold: 111,
    specializations: ["Residential", "Luxury Properties"],
    officeAddress: "Austin, Australia",
    agencyPhone: "+62 444 555 333",
    bio: baseBio,
    totalSalesValue: "$11M",
    clientSatisfaction: "98%",
    serviceAreas: [
      "Beverly Hills",
      "West Hollywood",
      "Bel Air",
      "Santa Monica",
      "Malibu",
    ],
    languages: [
      { name: "English", proficiency: "Native" },
      { name: "Spanish", proficiency: "Fluent" },
      { name: "French", proficiency: "Conversational" },
    ],
    performance: {
      avgSalePrice: "$2.4M",
      avgDaysOnMarket: "18 days",
      listToSaleRatio: "102%",
      responseTime: "< 1 hour",
    },
    socialLinks: {
      whatsapp: "#",
      instagram: "#",
      facebook: "#",
      sms: "#",
    },
    certifications: [
      "Certified Luxury Home Marketing Specialist (CLHMS)",
      "Accredited Buyer's Representative (ABR)",
      "Top 100 Agents in California (2021, 2022)",
    ],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["1", "2", "3", "4"],
    soldListingIds: ["5", "6", "7", "8"],
  },
  {
    id: "agent-2",
    slug: "anna-johnson",
    name: "Anna Johnson",
    title: "Luxury Property Specialist",
    agencyName: "Elders Real Estate",
    agencyLogo,
    phone: "+9999999998",
    email: "annajohnson@email.com",
    location: "Austin, Australia",
    licenseNumber: "22345678",
    rating: 4.8,
    reviewCount: 51,
    avatar: recommendAgent2,
    backgroundImage: roomBg,
    cardVariant: "framed",
    accent: "gold",
    yearsExperience: 12,
    propertiesSold: 128,
    specializations: ["Luxury Properties", "Investment"],
    officeAddress: "Sydney, Australia",
    agencyPhone: "+62 444 555 334",
    bio: baseBio,
    totalSalesValue: "$15M",
    clientSatisfaction: "99%",
    serviceAreas: ["Sydney CBD", "Bondi", "Paddington"],
    languages: [
      { name: "English", proficiency: "Native" },
      { name: "Italian", proficiency: "Conversational" },
    ],
    performance: {
      avgSalePrice: "$3.1M",
      avgDaysOnMarket: "14 days",
      listToSaleRatio: "104%",
      responseTime: "< 1 hour",
    },
    socialLinks: { whatsapp: "#", instagram: "#", facebook: "#" },
    certifications: ["Luxury Home Specialist", "Top Producer Award 2024"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["9", "10", "11", "12"],
    soldListingIds: ["13", "14", "15", "16"],
  },
  {
    id: "agent-3",
    slug: "michael-carter",
    name: "Michael Carter",
    title: "Commercial & Residential Advisor",
    agencyName: "Elders Real Estate",
    agencyLogo,
    phone: "+9999999997",
    email: "michaelcarter@email.com",
    location: "Austin, Australia",
    licenseNumber: "32345678",
    rating: 4.3,
    reviewCount: 29,
    avatar: recommendAgent1,
    backgroundImage: roomBg,
    cardVariant: "angled",
    accent: "blue",
    yearsExperience: 7,
    propertiesSold: 74,
    specializations: ["Commercial", "Residential"],
    officeAddress: "Melbourne, Australia",
    agencyPhone: "+62 444 555 335",
    bio: baseBio,
    totalSalesValue: "$8M",
    clientSatisfaction: "95%",
    serviceAreas: ["Melbourne CBD", "Docklands", "Richmond"],
    languages: [{ name: "English", proficiency: "Native" }],
    performance: {
      avgSalePrice: "$1.6M",
      avgDaysOnMarket: "21 days",
      listToSaleRatio: "99%",
      responseTime: "2 hours",
    },
    socialLinks: { whatsapp: "#", instagram: "#", facebook: "#" },
    certifications: ["Commercial Negotiation Expert"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["17", "18", "19", "20"],
    soldListingIds: ["21", "22", "23", "24"],
  },
  {
    id: "agent-4",
    slug: "brook-jones",
    name: "Brook Jones",
    title: "Rental & Investment Consultant",
    agencyName: "Elders Real Estate",
    agencyLogo,
    phone: "+9999999996",
    email: "brookjones@email.com",
    location: "Austin, Australia",
    licenseNumber: "42345678",
    rating: 4.6,
    reviewCount: 42,
    avatar: recommendAgent2,
    backgroundImage: roomBg,
    cardVariant: "framed",
    accent: "gold",
    yearsExperience: 10,
    propertiesSold: 96,
    specializations: ["Rentals", "Investment"],
    officeAddress: "Brisbane, Australia",
    agencyPhone: "+62 444 555 336",
    bio: baseBio,
    totalSalesValue: "$9.8M",
    clientSatisfaction: "97%",
    serviceAreas: ["Brisbane City", "New Farm", "Fortitude Valley"],
    languages: [{ name: "English", proficiency: "Native" }],
    performance: {
      avgSalePrice: "$1.9M",
      avgDaysOnMarket: "16 days",
      listToSaleRatio: "101%",
      responseTime: "< 1 hour",
    },
    socialLinks: { whatsapp: "#", instagram: "#", facebook: "#", sms: "#" },
    certifications: ["Certified Property Investment Advisor"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["25", "26", "27", "28"],
    soldListingIds: ["29", "30", "31", "32"],
  },
  {
    id: "agent-5",
    slug: "ash-fernando",
    name: "Ash Fernando",
    title: "Residential Sales Expert",
    agencyName: "Elders Real Estate",
    agencyLogo,
    phone: "+9999999995",
    email: "ash@email.com",
    location: "Austin, Australia",
    licenseNumber: "52345678",
    rating: 4.4,
    reviewCount: 33,
    avatar: recommendAgent1,
    backgroundImage: roomBg,
    cardVariant: "angled",
    accent: "red",
    yearsExperience: 8,
    propertiesSold: 82,
    specializations: ["Residential"],
    officeAddress: "Perth, Australia",
    agencyPhone: "+62 444 555 337",
    bio: baseBio,
    totalSalesValue: "$7.5M",
    clientSatisfaction: "96%",
    serviceAreas: ["Perth CBD", "Subiaco"],
    languages: [{ name: "English", proficiency: "Native" }],
    performance: {
      avgSalePrice: "$1.4M",
      avgDaysOnMarket: "19 days",
      listToSaleRatio: "100%",
      responseTime: "2 hours",
    },
    socialLinks: { whatsapp: "#", facebook: "#" },
    certifications: ["National Sales Excellence Award"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["33", "34", "35", "36"],
    soldListingIds: ["37", "38", "39", "40"],
  },
  {
    id: "agent-6",
    slug: "sophia-lee",
    name: "Sophia Lee",
    title: "Luxury & First Home Advisor",
    agencyName: "Elders Real Estate",
    agencyLogo,
    phone: "+9999999994",
    email: "sophialee@email.com",
    location: "Austin, Australia",
    licenseNumber: "62345678",
    rating: 4.7,
    reviewCount: 46,
    avatar: recommendAgent2,
    backgroundImage: roomBg,
    cardVariant: "framed",
    accent: "blue",
    yearsExperience: 11,
    propertiesSold: 103,
    specializations: ["Luxury Properties", "Residential"],
    officeAddress: "Gold Coast, Australia",
    agencyPhone: "+62 444 555 338",
    bio: baseBio,
    totalSalesValue: "$12.1M",
    clientSatisfaction: "98%",
    serviceAreas: ["Surfers Paradise", "Broadbeach"],
    languages: [
      { name: "English", proficiency: "Native" },
      { name: "Korean", proficiency: "Fluent" },
    ],
    performance: {
      avgSalePrice: "$2.2M",
      avgDaysOnMarket: "15 days",
      listToSaleRatio: "103%",
      responseTime: "< 1 hour",
    },
    socialLinks: { whatsapp: "#", instagram: "#", facebook: "#" },
    certifications: ["First Home Buyer Specialist"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],

    currentListingIds: ["41", "42", "43", "44"],
    soldListingIds: ["45", "46", "47", "48"],
  },
];
