import type { AgentDetail } from "@/lib/agents/types";
import recommendAgent1 from "@/public/recommendagent1.jpg";
import recommendAgent2 from "@/public/recommendagent2.png";
import roomBg from "@/public/roombgimg.svg";
import breifcase from "@/public/breifcase.svg";
import building from "@/public/building.svg";
import agencylogo1 from "@/public/elderrealestate.svg";

const baseBio =
  "Lorem ipsum dolor sit amet consectetur. Enim dolor est adipiscing consequat. Diam id auctor nunc sed id. Consectetur id risus tellus sed sed mi. Risus pretium proin nibh condimentum dui non. Lorem ipsum dolor sit amet consectetur. Elit adipiscing consequat. Diam id auctor nunc sed id. Consectetur id risus tellus est sed mi. Risus pretium proin nibh condimentum dui non.";

export const agentsCatalog: AgentDetail[] = [
  {
    id: "agent-1",
    slug: "katherine-fernandes",
    name: "Katherine Fernandes",
    title: "Senior Real Estate Agent",
    agencyName: "Elders Real Estate",
    agencyLogo: agencylogo1,
    phone: "+9999999999",
    email: "exampleemail.com",
    location: "Austin, Australia",
    licenseNumber: "12345678",
    rating: 4.5,
    reviewCount: 38,
    avatar: recommendAgent1,
    backgroundImage: roomBg,
    cardVariant: "angled",
    accent: "red",
    yearsExperience: 9,
    propertiesSold: 111,
    specializations: ["Residential", "Luxury Properties"],
    officeAddress: "Austin, Australia",
    agencyPhone: "+62 444 555 333",
    bio: baseBio,
    totalSalesValue: "$11M",
    clientSatisfaction: "98%",
    serviceAreas: [
      "Beverly Hills",
      "West Hollywood",
      "Bel Air",
      "Santa Monica",
      "Malibu",
    ],
    languages: [
      { name: "English", proficiency: "Native" },
      { name: "Spanish", proficiency: "Fluent" },
      { name: "French", proficiency: "Conversational" },
    ],
    performance: {
      avgSalePrice: "$2.4M",
      avgDaysOnMarket: "18 days",
      listToSaleRatio: "102%",
      responseTime: "< 1 hour",
    },
    socialLinks: {
      whatsapp: "#",
      instagram: "#",
      facebook: "#",
      sms: "#",
    },
    certifications: [
      "Certified Luxury Home Marketing Specialist (CLHMS)",
      "Accredited Buyer's Representative (ABR)",
      "Top 100 Agents in California (2021, 2022)",
    ],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["1", "2", "3", "4"],
    soldListingIds: ["5", "6", "7", "8"],
  },
  {
    id: "agent-2",
    slug: "anna-johnson",
    name: "Anna Johnson",
    title: "Luxury Property Specialist",
    agencyName: "Elders Real Estate",
    agencyLogo: agencylogo1,
    phone: "+9999999998",
    email: "annajohnson@email.com",
    location: "Austin, Australia",
    licenseNumber: "22345678",
    rating: 4.8,
    reviewCount: 51,
    avatar: recommendAgent2,
    backgroundImage: roomBg,
    cardVariant: "framed",
    accent: "gold",
    yearsExperience: 12,
    propertiesSold: 128,
    specializations: ["Luxury Properties", "Investment"],
    officeAddress: "Sydney, Australia",
    agencyPhone: "+62 444 555 334",
    bio: baseBio,
    totalSalesValue: "$15M",
    clientSatisfaction: "99%",
    serviceAreas: ["Sydney CBD", "Bondi", "Paddington"],
    languages: [
      { name: "English", proficiency: "Native" },
      { name: "Italian", proficiency: "Conversational" },
    ],
    performance: {
      avgSalePrice: "$3.1M",
      avgDaysOnMarket: "14 days",
      listToSaleRatio: "104%",
      responseTime: "< 1 hour",
    },
    socialLinks: { whatsapp: "#", instagram: "#", facebook: "#" },
    certifications: ["Luxury Home Specialist", "Top Producer Award 2024"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["9", "10", "11", "12"],
    soldListingIds: ["13", "14", "15", "16"],
  },
  {
    id: "agent-3",
    slug: "michael-carter",
    name: "Michael Carter",
    title: "Commercial & Residential Advisor",
    agencyName: "Elders Real Estate",
    agencyLogo: agencylogo1,
    phone: "+9999999997",
    email: "michaelcarter@email.com",
    location: "Austin, Australia",
    licenseNumber: "32345678",
    rating: 4.3,
    reviewCount: 29,
    avatar: recommendAgent1,
    backgroundImage: roomBg,
    cardVariant: "angled",
    accent: "blue",
    yearsExperience: 7,
    propertiesSold: 74,
    specializations: ["Commercial", "Residential"],
    officeAddress: "Melbourne, Australia",
    agencyPhone: "+62 444 555 335",
    bio: baseBio,
    totalSalesValue: "$8M",
    clientSatisfaction: "95%",
    serviceAreas: ["Melbourne CBD", "Docklands", "Richmond"],
    languages: [{ name: "English", proficiency: "Native" }],
    performance: {
      avgSalePrice: "$1.6M",
      avgDaysOnMarket: "21 days",
      listToSaleRatio: "99%",
      responseTime: "2 hours",
    },
    socialLinks: { whatsapp: "#", instagram: "#", facebook: "#" },
    certifications: ["Commercial Negotiation Expert"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["17", "18", "19", "20"],
    soldListingIds: ["21", "22", "23", "24"],
  },
  {
    id: "agent-4",
    slug: "brook-jones",
    name: "Brook Jones",
    title: "Rental & Investment Consultant",
    agencyName: "Elders Real Estate",
    agencyLogo: agencylogo1,
    phone: "+9999999996",
    email: "brookjones@email.com",
    location: "Austin, Australia",
    licenseNumber: "42345678",
    rating: 4.6,
    reviewCount: 42,
    avatar: recommendAgent2,
    backgroundImage: roomBg,
    cardVariant: "framed",
    accent: "gold",
    yearsExperience: 10,
    propertiesSold: 96,
    specializations: ["Rentals", "Investment"],
    officeAddress: "Brisbane, Australia",
    agencyPhone: "+62 444 555 336",
    bio: baseBio,
    totalSalesValue: "$9.8M",
    clientSatisfaction: "97%",
    serviceAreas: ["Brisbane City", "New Farm", "Fortitude Valley"],
    languages: [{ name: "English", proficiency: "Native" }],
    performance: {
      avgSalePrice: "$1.9M",
      avgDaysOnMarket: "16 days",
      listToSaleRatio: "101%",
      responseTime: "< 1 hour",
    },
    socialLinks: { whatsapp: "#", instagram: "#", facebook: "#", sms: "#" },
    certifications: ["Certified Property Investment Advisor"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["25", "26", "27", "28"],
    soldListingIds: ["29", "30", "31", "32"],
  },
  {
    id: "agent-5",
    slug: "ash-fernando",
    name: "Ash Fernando",
    title: "Residential Sales Expert",
    agencyName: "Elders Real Estate",
    agencyLogo: agencylogo1,
    phone: "+9999999995",
    email: "ash@email.com",
    location: "Austin, Australia",
    licenseNumber: "52345678",
    rating: 4.4,
    reviewCount: 33,
    avatar: recommendAgent1,
    backgroundImage: roomBg,
    cardVariant: "angled",
    accent: "red",
    yearsExperience: 8,
    propertiesSold: 82,
    specializations: ["Residential"],
    officeAddress: "Perth, Australia",
    agencyPhone: "+62 444 555 337",
    bio: baseBio,
    totalSalesValue: "$7.5M",
    clientSatisfaction: "96%",
    serviceAreas: ["Perth CBD", "Subiaco"],
    languages: [{ name: "English", proficiency: "Native" }],
    performance: {
      avgSalePrice: "$1.4M",
      avgDaysOnMarket: "19 days",
      listToSaleRatio: "100%",
      responseTime: "2 hours",
    },
    socialLinks: { whatsapp: "#", facebook: "#" },
    certifications: ["National Sales Excellence Award"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["33", "34", "35", "36"],
    soldListingIds: ["37", "38", "39", "40"],
  },
  {
    id: "agent-6",
    slug: "sophia-lee",
    name: "Sophia Lee",
    title: "Luxury & First Home Advisor",
    agencyName: "Elders Real Estate",
    agencyLogo: agencylogo1,
    phone: "+9999999994",
    email: "sophialee@email.com",
    location: "Austin, Australia",
    licenseNumber: "62345678",
    rating: 4.7,
    reviewCount: 46,
    avatar: recommendAgent2,
    backgroundImage: roomBg,
    cardVariant: "framed",
    accent: "blue",
    yearsExperience: 11,
    propertiesSold: 103,
    specializations: ["Luxury Properties", "Residential"],
    officeAddress: "Gold Coast, Australia",
    agencyPhone: "+62 444 555 338",
    bio: baseBio,
    totalSalesValue: "$12.1M",
    clientSatisfaction: "98%",
    serviceAreas: ["Surfers Paradise", "Broadbeach"],
    languages: [
      { name: "English", proficiency: "Native" },
      { name: "Korean", proficiency: "Fluent" },
    ],
    performance: {
      avgSalePrice: "$2.2M",
      avgDaysOnMarket: "15 days",
      listToSaleRatio: "103%",
      responseTime: "< 1 hour",
    },
    socialLinks: { whatsapp: "#", instagram: "#", facebook: "#" },
    certifications: ["First Home Buyer Specialist"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],

    currentListingIds: ["41", "42", "43", "44"],
    soldListingIds: ["45", "46", "47", "48"],
  },
  {
    id: "agent-7",
    slug: "olivia-martin",
    name: "Olivia Martin",
    title: "Family Home Specialist",
    agencyName: "Elders Real Estate",
    agencyLogo: agencylogo1,
    phone: "+9999999993",
    email: "oliviamartin@email.com",
    location: "Austin, Australia",
    licenseNumber: "72345678",
    rating: 4.6,
    reviewCount: 44,
    avatar: recommendAgent1,
    backgroundImage: roomBg,
    cardVariant: "angled",
    accent: "red",
    yearsExperience: 10,
    propertiesSold: 91,
    specializations: ["Residential", "Rentals"],
    officeAddress: "Adelaide, Australia",
    agencyPhone: "+62 444 555 339",
    bio: baseBio,
    totalSalesValue: "$10.4M",
    clientSatisfaction: "97%",
    serviceAreas: ["Adelaide CBD", "Norwood", "Glenelg"],
    languages: [{ name: "English", proficiency: "Native" }],
    performance: {
      avgSalePrice: "$1.8M",
      avgDaysOnMarket: "17 days",
      listToSaleRatio: "101%",
      responseTime: "< 1 hour",
    },
    socialLinks: { whatsapp: "#", instagram: "#", facebook: "#" },
    certifications: ["Residential Sales Specialist"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["49", "50", "51", "52"],
    soldListingIds: ["53", "54", "55", "56"],
  },
  {
    id: "agent-8",
    slug: "liam-anderson",
    name: "Liam Anderson",
    title: "Commercial Property Advisor",
    agencyName: "Elders Real Estate",
    agencyLogo: agencylogo1,
    phone: "+9999999992",
    email: "liamanderson@email.com",
    location: "Austin, Australia",
    licenseNumber: "82345678",
    rating: 4.5,
    reviewCount: 37,
    avatar: recommendAgent2,
    backgroundImage: roomBg,
    cardVariant: "framed",
    accent: "blue",
    yearsExperience: 9,
    propertiesSold: 87,
    specializations: ["Commercial", "Investment"],
    officeAddress: "Canberra, Australia",
    agencyPhone: "+62 444 555 340",
    bio: baseBio,
    totalSalesValue: "$9.3M",
    clientSatisfaction: "96%",
    serviceAreas: ["Canberra City", "Kingston", "Braddon"],
    languages: [{ name: "English", proficiency: "Native" }],
    performance: {
      avgSalePrice: "$2.1M",
      avgDaysOnMarket: "20 days",
      listToSaleRatio: "100%",
      responseTime: "2 hours",
    },
    socialLinks: { whatsapp: "#", instagram: "#", facebook: "#", sms: "#" },
    certifications: ["Commercial Property Certified Advisor"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["57", "58", "59", "60"],
    soldListingIds: ["61", "62", "63", "64"],
  },
  {
    id: "agent-9",
    slug: "emma-clarke",
    name: "Emma Clarke",
    title: "Luxury Estates Consultant",
    agencyName: "Elders Real Estate",
    agencyLogo: agencylogo1,
    phone: "+9999999991",
    email: "emmaclarke@email.com",
    location: "Austin, Australia",
    licenseNumber: "92345678",
    rating: 4.9,
    reviewCount: 58,
    avatar: recommendAgent1,
    backgroundImage: roomBg,
    cardVariant: "angled",
    accent: "gold",
    yearsExperience: 13,
    propertiesSold: 136,
    specializations: ["Luxury Properties", "Investment"],
    officeAddress: "Sydney, Australia",
    agencyPhone: "+62 444 555 341",
    bio: baseBio,
    totalSalesValue: "$18M",
    clientSatisfaction: "99%",
    serviceAreas: ["Mosman", "Double Bay", "Vaucluse"],
    languages: [
      { name: "English", proficiency: "Native" },
      { name: "Mandarin", proficiency: "Conversational" },
    ],
    performance: {
      avgSalePrice: "$3.6M",
      avgDaysOnMarket: "13 days",
      listToSaleRatio: "105%",
      responseTime: "< 1 hour",
    },
    socialLinks: { whatsapp: "#", instagram: "#", facebook: "#" },
    certifications: ["Certified Luxury Home Marketing Specialist"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["65", "66", "67", "68"],
    soldListingIds: ["69", "70", "71", "72"],
  },
  {
    id: "agent-10",
    slug: "noah-williams",
    name: "Noah Williams",
    title: "Land & Rural Sales Agent",
    agencyName: "Elders Real Estate",
    agencyLogo: agencylogo1,
    phone: "+9999999990",
    email: "noahwilliams@email.com",
    location: "Austin, Australia",
    licenseNumber: "10345678",
    rating: 4.4,
    reviewCount: 31,
    avatar: recommendAgent2,
    backgroundImage: roomBg,
    cardVariant: "framed",
    accent: "red",
    yearsExperience: 8,
    propertiesSold: 79,
    specializations: ["Residential", "Commercial"],
    officeAddress: "Hobart, Australia",
    agencyPhone: "+62 444 555 342",
    bio: baseBio,
    totalSalesValue: "$7.9M",
    clientSatisfaction: "95%",
    serviceAreas: ["Hobart", "Kingston", "Sandy Bay"],
    languages: [{ name: "English", proficiency: "Native" }],
    performance: {
      avgSalePrice: "$1.5M",
      avgDaysOnMarket: "23 days",
      listToSaleRatio: "99%",
      responseTime: "2 hours",
    },
    socialLinks: { whatsapp: "#", facebook: "#" },
    certifications: ["Rural Property Sales Specialist"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["73", "74", "75", "76"],
    soldListingIds: ["77", "78", "79", "80"],
  },
  {
    id: "agent-11",
    slug: "mia-thompson",
    name: "Mia Thompson",
    title: "Rental Market Specialist",
    agencyName: "Elders Real Estate",
    agencyLogo: agencylogo1,
    phone: "+9999999989",
    email: "miathompson@email.com",
    location: "Austin, Australia",
    licenseNumber: "11345678",
    rating: 4.7,
    reviewCount: 49,
    avatar: recommendAgent1,
    backgroundImage: roomBg,
    cardVariant: "angled",
    accent: "blue",
    yearsExperience: 11,
    propertiesSold: 108,
    specializations: ["Rentals", "Residential"],
    officeAddress: "Darwin, Australia",
    agencyPhone: "+62 444 555 343",
    bio: baseBio,
    totalSalesValue: "$11.2M",
    clientSatisfaction: "98%",
    serviceAreas: ["Darwin City", "Larrakeyah", "Fannie Bay"],
    languages: [
      { name: "English", proficiency: "Native" },
      { name: "Hindi", proficiency: "Conversational" },
    ],
    performance: {
      avgSalePrice: "$2M",
      avgDaysOnMarket: "16 days",
      listToSaleRatio: "102%",
      responseTime: "< 1 hour",
    },
    socialLinks: { whatsapp: "#", instagram: "#", facebook: "#", sms: "#" },
    certifications: ["Rental Property Management Specialist"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["81", "82", "83", "84"],
    soldListingIds: ["85", "86", "87", "88"],
  },
  {
    id: "agent-12",
    slug: "ethan-brooks",
    name: "Ethan Brooks",
    title: "Investment Property Consultant",
    agencyName: "Elders Real Estate",
    agencyLogo: agencylogo1,
    phone: "+9999999988",
    email: "ethanbrooks@email.com",
    location: "Austin, Australia",
    licenseNumber: "12345679",
    rating: 4.5,
    reviewCount: 35,
    avatar: recommendAgent2,
    backgroundImage: roomBg,
    cardVariant: "framed",
    accent: "gold",
    yearsExperience: 9,
    propertiesSold: 93,
    specializations: ["Investment", "Commercial"],
    officeAddress: "Newcastle, Australia",
    agencyPhone: "+62 444 555 344",
    bio: baseBio,
    totalSalesValue: "$10.8M",
    clientSatisfaction: "96%",
    serviceAreas: ["Newcastle", "Merewether", "Hamilton"],
    languages: [{ name: "English", proficiency: "Native" }],
    performance: {
      avgSalePrice: "$1.7M",
      avgDaysOnMarket: "18 days",
      listToSaleRatio: "101%",
      responseTime: "2 hours",
    },
    socialLinks: { whatsapp: "#", instagram: "#", facebook: "#" },
    certifications: ["Property Investment Advisor"],
    careerHighlights: [
      {
        title: "Senior Real Estate Agent",
        careericons: breifcase,
        company: "EstatePrime Realty",
        duration: "• 2018 - Present",
        description:
          "Leading luxury property sales division, consistently ranking in top 5% of agents nationwide. Specialized in high-value residential transactions and investment properties.",
      },
      {
        title: "Real Estate Agent",
        careericons: building,
        company: "Premier Properties Group",
        duration: "• 2011 - 2018",
        description:
          "Built strong client base through exceptional service and market expertise. Achieved top producer status for 5 consecutive years.",
      },
    ],
    currentListingIds: ["89", "90", "91", "92"],
    soldListingIds: ["93", "94", "95", "96"],
  },
];
